"use client";

import {
  createContext,
  useCallback,
  useContext,
  useEffect,
  useMemo,
  useSyncExternalStore,
  type ReactNode,
} from "react";

import { createPersistentStore } from "@/lib/persistent-store";

/** ColList ships in exactly two languages. Nothing else is supported. */
export const LANGUAGES = ["en", "ru"] as const;
export type Language = (typeof LANGUAGES)[number];

export const LANGUAGE_LABELS: Record<Language, { code: string; native: string }> = {
  en: { code: "EN", native: "English" },
  ru: { code: "RU", native: "Русский" },
};

/**
 * Sprint 1 scope: only the strings the navigation bar renders.
 * Sections add their own keys as they are built.
 */
const dictionary = {
  en: {
    "nav.matches": "Matches",
    "nav.diagnostic": "Diagnostic",
    "nav.roadmap": "Roadmap",
    "nav.cta": "Start Journey",
    "nav.tagline": "Full-Funding Navigator",
    "nav.language": "Language",
    "nav.theme": "Toggle day and night",
    "hero.eyebrow": "100% Full-Funding Navigator",
    "hero.headline": "Get accepted into",
    "hero.target.ivy": "the Ivy League",
    "hero.target.t20": "T20 Universities",
    "hero.target.nyuad": "NYU Abu Dhabi",
    "hero.target.asia": "Asian Tech Hubs",
    "hero.target.lac": "Full-Ride LACs",
    "hero.subtitle": "ColList maps the universities that cover tuition, housing and stipend in full — for 10th–12th graders and gap-year reappliers who refuse to pay sticker price.",
    "hero.cta": "Find Your Future",
    "hero.scrollHint": "See where the money is",
    "marquee.label": "Institutions with full-need or full-ride commitments",
    "marquee.disclaimer": "Demo Data",
    "aid.needBlind": "Need-Blind",
    "aid.fullNeed": "Full Need Met",
    "aid.fullRide": "Full Ride",
    "aid.fullScholarship": "Full Scholarship",
    "aid.noLoan": "No-Loan",
    "ascii.caption": "Built for students who earn their place, not buy it",
    "ob.title": "Starting Point Diagnostic",
    "ob.step": "Step",
    "ob.of": "of",
    "ob.next": "Next",
    "ob.back": "Back",
    "ob.finish": "Build my list",
    "ob.close": "Close",
    "ob.skip": "I'll do this later",
    "ob.optional": "Optional",
    "ob.s1.title": "Where are you right now?",
    "ob.s1.subtitle": "Timeline drives everything — the same GPA means different things in 10th grade and in January of 12th.",
    "ob.grade.10th": "10th grade",
    "ob.grade.11th": "11th grade",
    "ob.grade.12th": "12th grade",
    "ob.grade.gap-year": "Gap-year reapplicant",
    "ob.grade.10th.note": "Long runway. PSAT practice and GPA trajectory matter more than test scores right now.",
    "ob.grade.11th.note": "The decisive year. Your GPA is close to final and testing should start this spring.",
    "ob.grade.12th.note": "Urgent. Deadlines and financial aid forms take priority over new test attempts.",
    "ob.grade.gap-year.note": "Rebuild the weak half of last cycle: scores, essays, or the funding strategy itself.",
    "ob.s2.title": "Your academic standing",
    "ob.s2.subtitle": "Only GPA is needed. Every test score here is optional — leave it blank and your list still builds.",
    "ob.gpa": "GPA",
    "ob.gpaScale": "Scale",
    "ob.scale4": "4.0",
    "ob.scale5": "5.0 (CIS)",
    "ob.gpaEquiv": "4.0 equivalent",
    "ob.sat": "SAT / ACT",
    "ob.satPlaceholder": "e.g. 1450",
    "ob.satStatus.taken": "Already taken",
    "ob.satStatus.planned": "Not taken yet / plan to take",
    "ob.satStatus.optional": "Applying test-optional",
    "ob.satOptionalNote": "SAT ignored in matching. Strong full-funding options remain, but need-blind US schools get harder.",
    "ob.satPlannedNote": "Add the score whenever you have it — nothing here is blocked without it.",
    "ob.english": "English proficiency",
    "ob.englishTest": "Test",
    "ob.scorePlaceholder": "Score",
    "ob.engStatus.taken": "Already taken",
    "ob.engStatus.planned": "Not taken yet / plan to take",
    "ob.engStatus.optional": "Not required for my targets",
    "ob.s3.title": "Activities and honors",
    "ob.s3.subtitle": "Entirely optional. Add what you have — plenty of fully funded applicants arrive with a short list.",
    "ob.act.heading": "Activities",
    "ob.act.add": "Add activity",
    "ob.act.empty": "Nothing here yet. Add your strongest commitment first, or move on — this step never blocks you.",
    "ob.act.title": "Activity title",
    "ob.act.role": "Role / organisation",
    "ob.act.desc": "What you did",
    "ob.act.tier": "Tier",
    "ob.act.remove": "Remove",
    "ob.act.full": "Maximum of 10 reached",
    "ob.act.untitled": "Untitled activity",
    "ob.hon.heading": "Honors & awards",
    "ob.hon.add": "Add honor",
    "ob.hon.empty": "No awards listed. Optional — many funded applicants have none at all.",
    "ob.hon.title": "Award title",
    "ob.hon.level": "Recognition level",
    "ob.hon.grade": "Grade awarded",
    "ob.hon.remove": "Remove",
    "ob.hon.full": "Maximum of 5 reached",
    "ob.hon.untitled": "Untitled award",
    "ob.tier.olympiadsResearch": "Olympiads / Research",
    "ob.tier.leadershipProjects": "Leadership / Projects",
    "ob.tier.communityVarsity": "Community / Varsity",
    "ob.level.International": "International",
    "ob.level.National": "National",
    "ob.level.Regional": "Regional",
    "ob.level.School": "School",
    "ob.awardGrade.9th": "9th",
    "ob.awardGrade.10th": "10th",
    "ob.awardGrade.11th": "11th",
    "ob.awardGrade.12th": "12th",
    "ob.charsLeft": "characters left",
    "ob.s4.title": "Where would you go?",
    "ob.s4.subtitle": "Full funding is assumed throughout — ColList only surfaces universities that cover the whole cost.",
    "ob.region.anywhere": "Open to anywhere",
    "ob.region.US": "United States",
    "ob.region.Middle East": "Middle East",
    "ob.region.Europe": "Europe",
    "ob.region.Asia": "Asia",
    "ob.region.anywhereNote": "Global full-funding priority — every region stays in play.",
    "ob.regionHint": "Optional. Picking regions only nudges ranking; a fully funded university is never hidden because of this answer.",
    "ob.s5.title": "What will you study?",
    "ob.s5.subtitle": "This shapes which funding programmes and departments get weighted.",
    "ob.major.cs": "Computer Science / AI",
    "ob.major.engineering": "Engineering",
    "ob.major.sciences": "Natural Sciences",
    "ob.major.business": "Business & Quantitative Finance",
    "ob.major.humanities": "Humanities",
    "ob.done.title": "Profile saved",
    "ob.done.subtitle": "Here is what ColList will match against. Change any answer and your list rebuilds.",
    "ob.done.grade": "Timeline",
    "ob.done.gpa": "GPA",
    "ob.done.testing": "Testing",
    "ob.done.activities": "Activities",
    "ob.done.honors": "Honors",
    "ob.done.regions": "Regions",
    "ob.done.major": "Field",
    "ob.done.next": "The 8-college matrix arrives in the next release — your answers are stored and ready for it.",
    "ob.done.cta": "Done",
    "ob.done.anyRegion": "Open to anywhere",
    "ob.done.noMajor": "Undecided",
    "ob.done.testOptional": "Test-optional",
    "ob.done.none": "None yet",
    "ob.notTaken": "Not taken yet",
    "dash.eyebrow": "Point A Baseline",
    "dash.title": "Starting Point Profile Index",
    "dash.subtitle": "Where you stand today, before a single application is written.",
    "dash.academic": "Academic Fitness",
    "dash.testing": "Testing Readiness",
    "dash.ecDensity": "Activities & Honors",
    "dash.aid": "100% Full-Funding Aid Index",
    "dash.edit": "Edit Baseline Profile",
    "dash.notes": "Diagnostic notes",
    "dash.show": "Show",
    "dash.hide": "Hide",
    "dash.testOptionalActive": "Test-Optional Strategy Active",
    "dash.testingUnlocked": "Testing Potential Unlocked",
    "dash.noScores": "No scores logged yet",
    "dash.activities": "Activities",
    "dash.honors": "Honors",
    "dash.tierMix": "Tier mix",
    "dash.none": "None logged",
    "dash.kind.strength": "Strength",
    "dash.kind.gap": "Gap",
    "dash.kind.action": "Do next",
    "dash.aidReady": "Competitive for full-ride pools",
    "dash.aidBuilding": "Still building toward full-ride",
    "dash.of100": "of 100",
    "match.eyebrow": "Dual-Odds Roster",
    "match.title": "Your 8-College Matrix",
    "match.subtitle": "Every university here funds the full cost. The two figures are independent: getting in, and getting it paid for.",
    "match.admissions": "Admissions odds",
    "match.funding": "Full-funding viability",
    "match.inspect": "Inspect Match Details",
    "match.close": "Close",
    "match.cat.Dream": "Dream",
    "match.cat.Target": "Target",
    "match.cat.Safety": "Safety",
    "match.fund.needBlind": "100% Need-Blind",
    "match.fund.merit": "Full-Ride Merit",
    "match.fund.tuition": "Full-Tuition + Stipend",
    "match.cost": "Cost breakdown",
    "match.coa": "Cost of attendance",
    "match.netPrice": "Your target net price",
    "match.perYear": "per year",
    "match.coaNote": "Sticker price. ColList only lists universities that can take this to zero.",
    "match.gapTitle": "Profile fit vs requirements",
    "match.you": "You",
    "match.benchmark": "Benchmark",
    "match.gpaRow": "GPA (4.0 equivalent)",
    "match.satRow": "SAT",
    "match.englishRow": "English (IELTS equivalent)",
    "match.neutral": "Not submitted",
    "match.meets": "Meets",
    "match.below": "Below",
    "match.whys": "Strategic edge",
    "match.regionBoosted": "Preferred region",
    "match.recalcNote": "Updates the moment your baseline profile changes.",
    "vibe.button": "AI Vibe Check",
    "vibe.title": "Campus Vibe Check",
    "vibe.index": "Culture Fit",
    "vibe.close": "Close",
    "vibe.loading": "Reading campus signals",
    "vibe.source.gemini": "Live AI analysis",
    "vibe.source.fallback": "Offline culture profile",
    "vibe.error": "Could not load the vibe check.",
    "vibe.retry": "Try again",
    "vibe.dimensions": "Culture dimensions",
    "vibe.dim.academicIntensity": "Academic Intensity",
    "vibe.dim.collaboration": "Collaboration Level",
    "vibe.dim.globalPrestige": "Global Prestige",
    "vibe.dim.internationalInclusivity": "International Inclusivity",
    "vibe.dim.workLifeBalance": "Work-Life Balance",
    "vibe.stress": "Student stress index",
    "vibe.pulse": "Student pulse",
    "vibe.feeder": "Feeder strength",
    "vibe.feeder.tech": "Tech",
    "vibe.feeder.quant": "Quant & Finance",
    "vibe.feeder.gradSchool": "Grad School",
    "vibe.feeder.alumniLeverage": "Alumni Network",
    "vibe.cis": "CIS & international standing",
    "vibe.pros": "Why it fits you",
    "vibe.tradeoffs": "Honest trade-offs",
    "vibe.cis.exceptional": "Exceptional",
    "vibe.cis.strong": "Strong",
    "vibe.cis.moderate": "Moderate",
  },
  ru: {
    "nav.matches": "Подборка",
    "nav.diagnostic": "Диагностика",
    "nav.roadmap": "Дорожная карта",
    "nav.cta": "Начать путь",
    "nav.tagline": "Навигатор полного финансирования",
    "nav.language": "Язык",
    "nav.theme": "Переключить день и ночь",
    "hero.eyebrow": "Навигатор 100% финансирования",
    "hero.headline": "Поступай в",
    "hero.target.ivy": "Лигу плюща",
    "hero.target.t20": "топ-20 университетов",
    "hero.target.nyuad": "NYU Abu Dhabi",
    "hero.target.asia": "технохабы Азии",
    "hero.target.lac": "колледжи с полным грантом",
    "hero.subtitle": "ColList показывает университеты, которые полностью покрывают обучение, проживание и стипендию — для учеников 10–12 классов и тех, кто подаётся повторно после gap year.",
    "hero.cta": "Найти университет",
    "hero.scrollHint": "Посмотреть, где деньги",
    "marquee.label": "Университеты с полным покрытием расходов",
    "marquee.disclaimer": "Демо-данные",
    "aid.needBlind": "Need-Blind",
    "aid.fullNeed": "Полное покрытие нужды",
    "aid.fullRide": "Полный грант",
    "aid.fullScholarship": "Полная стипендия",
    "aid.noLoan": "Без кредитов",
    "ascii.caption": "Для тех, кто заслуживает место, а не покупает его",
    "ob.title": "Диагностика стартовой точки",
    "ob.step": "Шаг",
    "ob.of": "из",
    "ob.next": "Далее",
    "ob.back": "Назад",
    "ob.finish": "Собрать список",
    "ob.close": "Закрыть",
    "ob.skip": "Заполню позже",
    "ob.optional": "Необязательно",
    "ob.s1.title": "На каком вы этапе?",
    "ob.s1.subtitle": "Сроки решают всё — один и тот же GPA в 10 классе и в январе 12-го значит разное.",
    "ob.grade.10th": "10 класс",
    "ob.grade.11th": "11 класс",
    "ob.grade.12th": "12 класс",
    "ob.grade.gap-year": "Повторная подача после gap year",
    "ob.grade.10th.note": "Времени много. Сейчас важнее траектория GPA и подготовка к PSAT, а не баллы тестов.",
    "ob.grade.11th.note": "Решающий год. GPA почти зафиксирован, тесты стоит начинать этой весной.",
    "ob.grade.12th.note": "Срочно. Дедлайны и формы на финансовую помощь важнее новых попыток тестов.",
    "ob.grade.gap-year.note": "Усильте слабую половину прошлого цикла: баллы, эссе или саму стратегию финансирования.",
    "ob.s2.title": "Академические показатели",
    "ob.s2.subtitle": "Нужен только GPA. Все баллы тестов необязательны — оставьте пустыми, список всё равно соберётся.",
    "ob.gpa": "GPA",
    "ob.gpaScale": "Шкала",
    "ob.scale4": "4.0",
    "ob.scale5": "5.0 (СНГ)",
    "ob.gpaEquiv": "эквивалент 4.0",
    "ob.sat": "SAT / ACT",
    "ob.satPlaceholder": "например, 1450",
    "ob.satStatus.taken": "Уже сдал",
    "ob.satStatus.planned": "Ещё не сдавал / планирую",
    "ob.satStatus.optional": "Подаюсь без тестов",
    "ob.satOptionalNote": "SAT не учитывается. Варианты с полным финансированием остаются, но need-blind вузы США станут сложнее.",
    "ob.satPlannedNote": "Добавьте балл, когда он появится — без него ничего не блокируется.",
    "ob.english": "Знание английского",
    "ob.englishTest": "Тест",
    "ob.scorePlaceholder": "Балл",
    "ob.engStatus.taken": "Уже сдал",
    "ob.engStatus.planned": "Ещё не сдавал / планирую",
    "ob.engStatus.optional": "Не требуется для моих вузов",
    "ob.s3.title": "Активности и награды",
    "ob.s3.subtitle": "Полностью необязательно. Добавьте то, что есть — многие с полным финансированием приходят с коротким списком.",
    "ob.act.heading": "Активности",
    "ob.act.add": "Добавить активность",
    "ob.act.empty": "Пока пусто. Добавьте самое сильное занятие или идите дальше — этот шаг ничего не блокирует.",
    "ob.act.title": "Название активности",
    "ob.act.role": "Роль / организация",
    "ob.act.desc": "Что вы делали",
    "ob.act.tier": "Уровень",
    "ob.act.remove": "Удалить",
    "ob.act.full": "Достигнут максимум — 10",
    "ob.act.untitled": "Без названия",
    "ob.hon.heading": "Награды и достижения",
    "ob.hon.add": "Добавить награду",
    "ob.hon.empty": "Наград пока нет. Необязательно — у многих с полным финансированием их нет вовсе.",
    "ob.hon.title": "Название награды",
    "ob.hon.level": "Уровень признания",
    "ob.hon.grade": "Класс получения",
    "ob.hon.remove": "Удалить",
    "ob.hon.full": "Достигнут максимум — 5",
    "ob.hon.untitled": "Без названия",
    "ob.tier.olympiadsResearch": "Олимпиады / Исследования",
    "ob.tier.leadershipProjects": "Лидерство / Проекты",
    "ob.tier.communityVarsity": "Сообщество / Спорт",
    "ob.level.International": "Международный",
    "ob.level.National": "Национальный",
    "ob.level.Regional": "Региональный",
    "ob.level.School": "Школьный",
    "ob.awardGrade.9th": "9 класс",
    "ob.awardGrade.10th": "10 класс",
    "ob.awardGrade.11th": "11 класс",
    "ob.awardGrade.12th": "12 класс",
    "ob.charsLeft": "символов осталось",
    "ob.s4.title": "Куда готовы поехать?",
    "ob.s4.subtitle": "Полное финансирование подразумевается везде — ColList показывает только вузы, покрывающие всю стоимость.",
    "ob.region.anywhere": "Открыт к любому региону",
    "ob.region.US": "США",
    "ob.region.Middle East": "Ближний Восток",
    "ob.region.Europe": "Европа",
    "ob.region.Asia": "Азия",
    "ob.region.anywhereNote": "Приоритет — полное финансирование по всему миру, все регионы остаются в игре.",
    "ob.regionHint": "Необязательно. Выбор регионов лишь влияет на ранжирование; вуз с полным финансированием никогда не скрывается из-за этого ответа.",
    "ob.s5.title": "Что будете изучать?",
    "ob.s5.subtitle": "От этого зависит, какие программы финансирования и факультеты получат приоритет.",
    "ob.major.cs": "Computer Science / ИИ",
    "ob.major.engineering": "Инженерия",
    "ob.major.sciences": "Естественные науки",
    "ob.major.business": "Бизнес и количественные финансы",
    "ob.major.humanities": "Гуманитарные науки",
    "ob.done.title": "Профиль сохранён",
    "ob.done.subtitle": "Вот с чем ColList будет сопоставлять. Измените любой ответ — список пересоберётся.",
    "ob.done.grade": "Этап",
    "ob.done.gpa": "GPA",
    "ob.done.testing": "Тесты",
    "ob.done.activities": "Активности",
    "ob.done.honors": "Награды",
    "ob.done.regions": "Регионы",
    "ob.done.major": "Направление",
    "ob.done.next": "Матрица из 8 университетов появится в следующем релизе — ваши ответы уже сохранены для неё.",
    "ob.done.cta": "Готово",
    "ob.done.anyRegion": "Любой регион",
    "ob.done.noMajor": "Не определено",
    "ob.done.testOptional": "Без тестов",
    "ob.done.none": "Пока нет",
    "ob.notTaken": "Ещё не сдавал",
    "dash.eyebrow": "Базовая точка А",
    "dash.title": "Индекс стартовой точки",
    "dash.subtitle": "Где вы сейчас — до того, как написана хоть одна заявка.",
    "dash.academic": "Академическая форма",
    "dash.testing": "Готовность по тестам",
    "dash.ecDensity": "Активности и награды",
    "dash.aid": "Индекс 100% финансирования",
    "dash.edit": "Изменить базовый профиль",
    "dash.notes": "Диагностические заметки",
    "dash.show": "Показать",
    "dash.hide": "Скрыть",
    "dash.testOptionalActive": "Стратегия без тестов активна",
    "dash.testingUnlocked": "Есть запас по тестам",
    "dash.noScores": "Баллы ещё не внесены",
    "dash.activities": "Активности",
    "dash.honors": "Награды",
    "dash.tierMix": "Распределение уровней",
    "dash.none": "Пока ничего",
    "dash.kind.strength": "Сильная сторона",
    "dash.kind.gap": "Пробел",
    "dash.kind.action": "Следующий шаг",
    "dash.aidReady": "Конкурентоспособен для полных грантов",
    "dash.aidBuilding": "Ещё набирает силу для полных грантов",
    "dash.of100": "из 100",
    "match.eyebrow": "Двойные шансы",
    "match.title": "Ваша матрица из 8 университетов",
    "match.subtitle": "Каждый вуз здесь покрывает полную стоимость. Два показателя независимы: поступить и получить финансирование.",
    "match.admissions": "Шансы на поступление",
    "match.funding": "Вероятность полного финансирования",
    "match.inspect": "Разобрать совпадение",
    "match.close": "Закрыть",
    "match.cat.Dream": "Мечта",
    "match.cat.Target": "Цель",
    "match.cat.Safety": "Надёжный",
    "match.fund.needBlind": "100% Need-Blind",
    "match.fund.merit": "Полный грант за заслуги",
    "match.fund.tuition": "Обучение + стипендия",
    "match.cost": "Разбор стоимости",
    "match.coa": "Полная стоимость обучения",
    "match.netPrice": "Ваша целевая стоимость",
    "match.perYear": "в год",
    "match.coaNote": "Цена без скидок. ColList показывает только вузы, способные свести её к нулю.",
    "match.gapTitle": "Профиль против требований",
    "match.you": "Вы",
    "match.benchmark": "Ориентир",
    "match.gpaRow": "GPA (эквивалент 4.0)",
    "match.satRow": "SAT",
    "match.englishRow": "Английский (эквивалент IELTS)",
    "match.neutral": "Не подан",
    "match.meets": "Соответствует",
    "match.below": "Ниже",
    "match.whys": "Стратегическое преимущество",
    "match.regionBoosted": "Предпочтительный регион",
    "match.recalcNote": "Обновляется сразу при изменении базового профиля.",
    "vibe.button": "AI-проверка атмосферы",
    "vibe.title": "Атмосфера кампуса",
    "vibe.index": "Совпадение культуры",
    "vibe.close": "Закрыть",
    "vibe.loading": "Считываем сигналы кампуса",
    "vibe.source.gemini": "Живой AI-анализ",
    "vibe.source.fallback": "Офлайн-профиль культуры",
    "vibe.error": "Не удалось загрузить проверку атмосферы.",
    "vibe.retry": "Повторить",
    "vibe.dimensions": "Измерения культуры",
    "vibe.dim.academicIntensity": "Академическая интенсивность",
    "vibe.dim.collaboration": "Уровень сотрудничества",
    "vibe.dim.globalPrestige": "Мировой престиж",
    "vibe.dim.internationalInclusivity": "Открытость к иностранцам",
    "vibe.dim.workLifeBalance": "Баланс учёбы и жизни",
    "vibe.stress": "Индекс стресса студентов",
    "vibe.pulse": "Пульс студентов",
    "vibe.feeder": "Сила трудоустройства",
    "vibe.feeder.tech": "Технологии",
    "vibe.feeder.quant": "Финансы и quant",
    "vibe.feeder.gradSchool": "Аспирантура",
    "vibe.feeder.alumniLeverage": "Сеть выпускников",
    "vibe.cis": "Положение студентов из СНГ",
    "vibe.pros": "Почему подходит вам",
    "vibe.tradeoffs": "Честные компромиссы",
    "vibe.cis.exceptional": "Исключительное",
    "vibe.cis.strong": "Сильное",
    "vibe.cis.moderate": "Умеренное",
  },
} as const;

export type TranslationKey = keyof (typeof dictionary)["en"];

function isLanguage(value: unknown): value is Language {
  return typeof value === "string" && (LANGUAGES as readonly string[]).includes(value);
}

const languageStore = createPersistentStore<Language>("collist.language", "en", isLanguage);

type LanguageContextValue = {
  language: Language;
  setLanguage: (next: Language) => void;
  t: (key: TranslationKey) => string;
};

const LanguageContext = createContext<LanguageContextValue | null>(null);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const language = useSyncExternalStore(
    languageStore.subscribe,
    languageStore.getSnapshot,
    languageStore.getServerSnapshot,
  );

  // Keep the document language in sync for screen readers and hyphenation.
  useEffect(() => {
    document.documentElement.lang = language;
  }, [language]);

  const setLanguage = useCallback((next: Language) => {
    languageStore.set(next);
  }, []);

  const t = useCallback(
    (key: TranslationKey) => dictionary[language][key] ?? dictionary.en[key],
    [language],
  );

  const value = useMemo(
    () => ({ language, setLanguage, t }),
    [language, setLanguage, t],
  );

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used inside <LanguageProvider>.");
  }
  return context;
}
